name: Collect Hatena Data

on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'   # 毎時:20（UTC）

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug: list files
        run: |
          pwd
          ls -la
          echo '--- seeds.txt ---'
          sed -n '1,100p' seeds.txt || true

      - name: Install deps
        run: pip install requests

      - name: Run collector
        env:
          SEEDS_FILE: seeds.txt
          OUT_DIR: out
        run: python hatena_collect.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ github.run_id }}
          path: out/**/*
          if-no-files-found: warn
